[ARC-1895]Feature/app design part1
andguladzeshio/QuizApp pull request #1
Opened 2021-11-11 11:03 UTC by andguladzeshio

https://spaceneobank.atlassian.net/browse/ARC-1895

2021-11-13 08:00 UTC, giorgiqemoklidze approved these changes

2021-11-15 09:52 UTC, AnaRusadze requested changes

2021-11-15 09:52 UTC, AnaRusadze commented on app/src/main/java/com/example/quizapp/ui/adapter/SubjectRecyclerViewAdapter.kt
> +        holder.startButton.setOnClickListener { callbacks.startQuizCallback() }
with(holder)

2021-11-15 09:52 UTC, AnaRusadze commented on app/src/main/java/com/example/quizapp/ui/fragment/startpage/StartPageFragment.kt
> +            Toast.makeText(requireContext(), "გთხოვთ შეიყვანოთ სახელი", Toast.LENGTH_SHORT).show()
ტოუსტის ექსთენშენი გააკეთე

2021-11-15 09:52 UTC, AnaRusadze commented on app/src/main/java/com/example/quizapp/views/CustomBackgroundView.kt
> +        paint.isAntiAlias = true
paint.isAntiAlias = true ორჯერ გიწერია

2021-11-15 09:52 UTC, AnaRusadze commented on app/src/main/java/com/example/quizapp/views/CustomBackgroundView.kt
> +            isUpsideDown = getBoolean(R.styleable.CustomBackgroundView_isUpsideDown, false)
isUpsideDown აღარ დაგჭირდება scaleYის გამო

2021-11-15 09:52 UTC, AnaRusadze commented on app/src/main/java/com/example/quizapp/views/CustomBackgroundView.kt
> +    private val oval: RectF = RectF(0f, 0f,0f,0f)
სცადე რომ ორი rect რომ არ დაიხატოს, path გამოიყენო, თავისი lineTo და arcTo ფუნქციებით

2021-11-15 09:52 UTC, AnaRusadze commented on app/src/main/res/values/strings.xml
> +    <string name="n_14">გამარჯობა, ხოსე \nბოლო კრედიტები: 14</string>
ამის სტრინგებში გატანა არ გჭირდება. tools ით შეგიძლია გამოაჩინო, 
ან  - გამარჯობა, %s \nბოლო კრედიტები: %d სახელის და ქულის არგუმენტები კოდიდან გადაეცი

2021-11-15 10:32 UTC, andguladzeshio commented on app/src/main/java/com/example/quizapp/ui/adapter/SubjectRecyclerViewAdapter.kt
> +        holder.startButton.setOnClickListener { callbacks.startQuizCallback() }
done

2021-11-15 10:32 UTC, andguladzeshio commented on app/src/main/java/com/example/quizapp/ui/fragment/startpage/StartPageFragment.kt
> +            Toast.makeText(requireContext(), "გთხოვთ შეიყვანოთ სახელი", Toast.LENGTH_SHORT).show()
done

2021-11-15 10:33 UTC, andguladzeshio commented on app/src/main/java/com/example/quizapp/views/CustomBackgroundView.kt
> +        paint.isAntiAlias = true
ეს თავიდან დავწერე სახელიც შევუცვალე და ატვირთვა დამავიწყდა ეტყობა ბრენჩზე ეხლა ავტვირთე სახელიც გადარქმეული აქვს ამ ვიუს
done

2021-11-15 10:33 UTC, andguladzeshio commented on app/src/main/java/com/example/quizapp/views/CustomBackgroundView.kt
> +            isUpsideDown = getBoolean(R.styleable.CustomBackgroundView_isUpsideDown, false)
done

2021-11-15 10:33 UTC, andguladzeshio commented on app/src/main/res/values/strings.xml
> +    <string name="n_14">გამარჯობა, ხოსე \nბოლო კრედიტები: 14</string>
done

2021-11-15 10:38 UTC, andguladzeshio commented on app/src/main/java/com/example/quizapp/views/CustomBackgroundView.kt
> +    private val oval: RectF = RectF(0f, 0f,0f,0f)
გავარკვევ ამას და გავაკეთებ დღეს

2021-11-15 10:55 UTC, andguladzeshio commented on app/src/main/java/com/example/quizapp/views/CustomBackgroundView.kt
> +    private val oval: RectF = RectF(0f, 0f,0f,0f)
drawArc(oval, startangle: 0f, sweepangle: 180f, true, paint) ამ ფუნქციით ვხატავ და მარტო ნახევარწრე იხატება overdraw აღარ ხდება, path-ითაც დაახლოებით რაღაც იგივე უნდა მექნა და დავტოვო ესე თუ path-ით გავაკეთო?

2021-11-15 13:23 UTC, andguladzeshio commented on app/src/main/java/com/example/quizapp/views/CustomBackgroundView.kt
> +    private val oval: RectF = RectF(0f, 0f,0f,0f)
done

2021-11-16 12:23 UTC, GiorgiMamagulashvili16 approved these changes

2021-11-17 11:51 UTC, AnaRusadze requested changes

2021-11-17 11:51 UTC, AnaRusadze commented on app/src/main/java/com/example/quizapp/ui/fragment/splash_screen/SplashScreenFragment.kt
> +            setHeightPercentage(0.3f)
ამას კოდის მხარეს რატომ უცვლი?

2021-11-17 11:51 UTC, AnaRusadze commented on app/src/main/java/com/example/quizapp/ui/fragment/splash_screen/SplashScreenFragment.kt
> +            radius = 0f
და რადიუსს

2021-11-17 11:51 UTC, AnaRusadze commented on app/src/main/java/com/example/quizapp/views/BlackArkView.kt
> +class BlackArkView @JvmOverloads constructor(
arc იწერება

2021-11-17 11:51 UTC, AnaRusadze commented on app/src/main/java/com/example/quizapp/views/BlackArkView.kt
> +        path.arcTo(-overFlow, 0f, measuredWidth.toFloat() + overFlow, 2 * radius, 180f, 180f, true)
path.apply{}

2021-11-17 11:51 UTC, AnaRusadze commented on app/src/main/java/com/example/quizapp/views/BlackArkView.kt
> +        path.arcTo(-overFlow, 0f, measuredWidth.toFloat() + overFlow, 2 * radius, 180f, 180f, true)
path.arcTo(-overFlow, 0f, measuredWidth.toFloat() + overFlow, 2 * radius, 180f, 180f, true) აქ ბოლო პარამეტრად forceMoveTo- false რომ დაწერო, რამე პრობლემა შეიქმნება?

2021-11-17 11:51 UTC, AnaRusadze commented on app/src/main/java/com/example/quizapp/views/BlackArkView.kt
> +        paint.color = ContextCompat.getColor(context, R.color.background_view_color)
paint.apply{}

2021-11-17 11:51 UTC, AnaRusadze commented on app/src/main/java/com/example/quizapp/views/BlackArkView.kt
> +class BlackArkView @JvmOverloads constructor(
სამომავლოდ ეგეთი ვიუ სხვა ფერით რომ დაგჭირდეს, black-ის გამოყენება სახელში ხელს შეგიშლის

2021-11-17 11:51 UTC, AnaRusadze commented on app/src/main/res/layout/fragment_home_page.xml
> +        android:id="@+id/customBackgroundView2"
bad name for id

2021-11-17 11:51 UTC, AnaRusadze commented on app/src/main/res/layout/subject_custom_layout.xml
> +        android:id="@+id/tv_subject"
აიდიების სახელი ზოგადად მიჩნეულია tvSubject camel case-ით დაიწყოს

2021-11-17 11:51 UTC, AnaRusadze commented on app/src/main/res/layout/subject_custom_layout.xml
> +    tools:ignore="PxUsage"
რადგანაც პიქსელის გამოყენება არაა რეკომენდირებული, შეგიძლია dpებზე გადაიყვანო და თვალით დასვა, ამჯერად დიზაინის ფაილის ბრალია ეგ გაურკვევლობა

2021-11-17 12:39 UTC, andguladzeshio commented on app/src/main/java/com/example/quizapp/ui/fragment/splash_screen/SplashScreenFragment.kt
> +            setHeightPercentage(0.3f)
ორი ვარიანტია სტარტაპის და თუ უკვე დალოგინებულია იუზერი სხვა სტილები  უნდა ქონდეს ვიუს

2021-11-17 12:39 UTC, andguladzeshio commented on app/src/main/java/com/example/quizapp/ui/fragment/splash_screen/SplashScreenFragment.kt
> +            radius = 0f
ოთხკუთხედი რომ იყოს აი ჰოუმ სქრინზე რაცაა ზემოდან

2021-11-17 13:14 UTC, andguladzeshio commented on app/src/main/java/com/example/quizapp/views/BlackArkView.kt
> +        path.arcTo(-overFlow, 0f, measuredWidth.toFloat() + overFlow, 2 * radius, 180f, 180f, true)
done

2021-11-17 13:14 UTC, andguladzeshio commented on app/src/main/java/com/example/quizapp/views/BlackArkView.kt
> +        paint.color = ContextCompat.getColor(context, R.color.background_view_color)
done

2021-11-17 13:14 UTC, andguladzeshio commented on app/src/main/res/layout/fragment_home_page.xml
> +        android:id="@+id/customBackgroundView2"
done

2021-11-17 13:14 UTC, andguladzeshio commented on app/src/main/res/layout/subject_custom_layout.xml
> +        android:id="@+id/tv_subject"
done

2021-11-17 13:14 UTC, andguladzeshio commented on app/src/main/res/layout/subject_custom_layout.xml
> +    tools:ignore="PxUsage"
done მგონი საკმარისად მივამსგავსე :D

2021-11-17 13:34 UTC, AnaRusadze requested changes

2021-11-17 13:34 UTC, AnaRusadze commented on app/src/main/res/layout/fragment_quiz_screen.xml
> +    tools:ignore="PxUsage">
არ გჭირდება tools:ignore="PxUsage"

2021-11-17 13:34 UTC, AnaRusadze commented on app/src/main/res/layout/fragment_quiz_screen.xml
> +
ზედმეტად ბევრი სფეისია

2021-11-17 13:34 UTC, AnaRusadze commented on app/src/main/res/layout/fragment_quiz_screen.xml
> +    tools:ignore="PxUsage">
/> -თ დაასრულე ხოლმე, თუ შიგნით სხვა ვიუები არ ჰყავს

2021-11-17 13:34 UTC, AnaRusadze commented on app/src/main/res/layout/subject_custom_layout.xml
> +        android:id="@+id/tv_description"
აიდის სახელი

2021-11-17 13:34 UTC, AnaRusadze commented on app/src/main/res/layout/subject_custom_layout.xml
> +        android:id="@+id/btn_start"
აიდის სახელი

2021-11-17 13:43 UTC, andguladzeshio commented on app/src/main/res/layout/fragment_quiz_screen.xml
> +
done

2021-11-17 13:43 UTC, andguladzeshio commented on app/src/main/res/layout/fragment_quiz_screen.xml
> +    tools:ignore="PxUsage">
done

2021-11-17 13:43 UTC, AnaRusadze approved these changes

2021-11-17 13:43 UTC, andguladzeshio commented on app/src/main/res/layout/subject_custom_layout.xml
> +        android:id="@+id/tv_description"
done

2021-11-17 13:43 UTC, andguladzeshio commented on app/src/main/res/layout/subject_custom_layout.xml
> +        android:id="@+id/btn_start"
done

2021-11-18 08:23 UTC, merged